### ISSUE TITLE
Generate private methods for mocked methods

### ISSUE THREAD

**Issue by arnzel** [SquaretestLLC/Squaretest#16]
Currently plugin generates for every mocked methods lines like this

`    when(myController.myService.getEntitiesByUuidAndLong(
        UUID.fromString("3d0c4f7f-763f-4bed-98, 0L)).thenReturn(Arrays.asList());
`

I think it would be nice if it would generate a private method instead which looks like 
`
  private void givenEntitiesByUuidAndLong(Uuid uuid,
      Long long,
      List<Object> entities ){
    when(myController.myService.getEntitiesByUuidAndLong
        .getEntitiesByUuidAndLong(uuid, long))
        .thenReturn(entities);
  }
`

and add a function call in the test

`
givenEntitiesByUuidAndLong(UUID.fromString("3d0c4f7f-763f-4bed-98, 0L,Arrays.asList())
`

**Comment by nate-dev** [comment]
Thank you for the feedback. I apologize for the delayed response. Squaretest is unable to accommodate this feature. 
The following workaround may help reduce duplicate code in the stubs generated by Squaretest. 
1. Right click the when(..) statement.
2. Select Refactor | Extract Method.
3. Select "when(..).thenReturn(..)".
4. Enter the name of the private method that will be created.
5. When IntelliJ shows the "Process Duplicates" dialog box, click "All".

IntelliJ will then replace the similar "when(..).thenReturn(..)" stubs with calls to the new helper method. Then, modify the generated helper method to return void instead of "OngoingStubbing".
