### ISSUE TITLE
Template for Given/When/Then

### ISSUE THREAD

**Issue by snijsure** [SquaretestLLC/Squaretest#22]
Is there a template definition that would allow one to generate tests of type

Given
When
Then

Instead of current method based simple description GWT tests is here - https://proandroiddev.com/given-when-then-style-on-android-development-using-junit5-f47388053573

**Comment by nate-dev** [comment]
Thank you for the feedback. There isn't a template for the Mockito given/when pattern at this time.
In the near term, the best way to generate given/when statements would be to modify one of the existing Mockito templates.

Longer term, the best way would be to add a QuickSetting to the top of the Mockito templates called: useBddMocks, then have the templates generate given/when statements when that is set to true. I can't commit to implementing this feature at this time. I will update this issue if that changes, though.

**Comment by nate-dev** [comment]
I added a Quick Setting to use MockitoBDD (given/willAnswer/etc) instead of the normal Mockito stubs. To use MockitoBDD, please modify the template(s) with the following changes.
Change line 13 from:
`#set($shouldUseMockitoBdd = false)`
to:
`#set($shouldUseMockitoBdd = true)`
Modifying the generated comments and the test names to follow given/then conventions will be up to the user.
